[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=6.2"]

build-backend = "setuptools.build_meta"

[project]
name = "imas-ibex"
authors = [
  {name = "IBEX Developers"},
  {name = "Olivier Hoenen", email = "olivier.hoenen@iter.org"}
]
description = "Data visualization for IMAS IDS data"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7"
license = {text = "LGPL-3.0-only"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: FastAPI",
    "Framework :: Pytest",
    "Framework :: Sphinx",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dynamic = ["version"]
dependencies = [
    "imas-idstools",
    "click",
    "uvicorn",
    "fastapi[standard]==0.115.14",
    "packaging",
    "tsdownsample",
    "orjson",
    "autodoc_pydantic",
    "scipy",
]

[project.optional-dependencies]
# these self-dependencies are available since pip 21.2
all = [
    "ibex[test]",
    "ibex[linting]",
    "ibex[docs]",
]

test = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
]

linting = [
    "ruff",
]

docs =[
    "sphinx>=7,<9",
    "sphinx-autosummary-accessors==2025.3.1",
    "sphinx_immaterial",
]

benchmark = [
    "asv==0.6.4",
]

[project.urls]
homepage = "https://github.com/iterorganization/IBEX"

[tool.setuptools.packages.find]
where = ["."]
include = ["ibex*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--strict-markers"
testpaths = "tests"

[tool.setuptools_scm]
write_to = "ibex/_version.py"
local_scheme = "no-local-version"
search_parent_directories = true

[tool.ruff]
# Set the maximum line length to 120.
line-length = 120
exclude = ["venv", "_version.py"]

[tool.coverage.run]
omit = [
    "ibex/_version.py",
    ]

[project.scripts]
run_ibex_service = "ibex.cli:main"
